# Generated by Django 2.2 on 2020-02-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.Post.photo_path_and_rename)),
                ('alt_text', models.CharField(blank=True, max_length=120, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('posted_at',),
            },
        ),
    ]
